"""
convert_cvat_to_yolo.py
-----------------------
Converts CVAT 1.1 XML bounding-box annotations into YOLO detection format
and organises the dataset into train / val / test splits.

Input layout (already present in the repo):
    dataset/
        cows/         ← raw images  (PNG / JPEG)
        annotations.xml  ← CVAT XML with <box> elements

Output layout (created by this script):
    dataset/processed/
        train/
            images/   ← .png/.jpg copies
            labels/   ← YOLO .txt files
        val/
            images/
            labels/
        test/
            images/
            labels/
        data.yaml     ← ready for ultralytics YOLO

YOLO label format per line:
    <class_id>  <cx_norm>  <cy_norm>  <w_norm>  <h_norm>
all values normalised [0, 1] by image width / height.
"""

import xml.etree.ElementTree as ET
import shutil
import random
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
SEED        = 42
TRAIN_RATIO = 0.70
VAL_RATIO   = 0.20
# TEST_RATIO  = 1 - TRAIN_RATIO - VAL_RATIO  = 0.10

PROJECT_ROOT  = Path(__file__).resolve().parent.parent
DATASET_DIR   = PROJECT_ROOT / "dataset"
IMAGES_SRC    = DATASET_DIR / "cows"          # raw images
ANNOTATIONS   = DATASET_DIR / "annotations.xml"
PROCESSED_DIR = DATASET_DIR / "processed"

CLASS_NAMES = ["cow"]   # single class


# ── Helpers ───────────────────────────────────────────────────────────────────

def parse_cvat_xml(xml_path: Path) -> dict:
    """
    Parse CVAT 1.1 XML and return a dict:
        { image_name (str) : { "width": int, "height": int,
                               "boxes": [(xtl, ytl, xbr, ybr), ...] } }
    """
    tree = ET.parse(xml_path)
    root = tree.getroot()

    data = {}
    for img_elem in root.findall("image"):
        name   = img_elem.get("name")       # e.g. "images/0.png"
        width  = int(img_elem.get("width"))
        height = int(img_elem.get("height"))

        # Strip any leading path component so we get just the filename
        stem = Path(name).name              # "0.png"

        boxes = []
        for box in img_elem.findall("box"):
            xtl = float(box.get("xtl"))
            ytl = float(box.get("ytl"))
            xbr = float(box.get("xbr"))
            ybr = float(box.get("ybr"))
            boxes.append((xtl, ytl, xbr, ybr))

        data[stem] = {"width": width, "height": height, "boxes": boxes}

    return data


def xyxy_to_yolo(xtl, ytl, xbr, ybr, img_w, img_h) -> str:
    """Convert absolute xyxy box to YOLO normalised cx cy w h string."""
    cx = (xtl + xbr) / 2.0 / img_w
    cy = (ytl + ybr) / 2.0 / img_h
    w  = (xbr - xtl) / img_w
    h  = (ybr - ytl) / img_h
    # Clamp to [0, 1] in case of annotation overshoot
    cx, cy, w, h = (max(0.0, min(1.0, v)) for v in (cx, cy, w, h))
    return f"0 {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}"


def write_yaml(out_dir: Path):
    yaml_content = f"""# Auto-generated by convert_cvat_to_yolo.py
path: {out_dir.as_posix()}
train: train/images
val:   val/images
test:  test/images

nc: {len(CLASS_NAMES)}
names: {CLASS_NAMES}
"""
    (out_dir / "data.yaml").write_text(yaml_content, encoding="utf-8")
    print(f"  Wrote {out_dir / 'data.yaml'}")


# ── Main ──────────────────────────────────────────────────────────────────────

def convert():
    print("=" * 60)
    print("CVAT XML -> YOLO Converter")
    print("=" * 60)

    # 1. Parse annotations
    print(f"\n[1/4] Parsing {ANNOTATIONS.name} ...")
    ann = parse_cvat_xml(ANNOTATIONS)
    print(f"      Found {len(ann)} annotated images, "
          f"{sum(len(v['boxes']) for v in ann.values())} total boxes")

    # 2. Match annotation entries to actual image files on disk
    all_image_files = sorted(IMAGES_SRC.glob("*"))
    matched = []
    skipped = []
    for img_path in all_image_files:
        stem = img_path.name          # e.g. "0.png"
        if stem in ann:
            matched.append((img_path, ann[stem]))
        else:
            skipped.append(img_path.name)

    if skipped:
        print(f"  [!]  No annotation found for: {skipped} --- skipped")
    print(f"      Matched {len(matched)} images")

    if not matched:
        raise RuntimeError("No images matched annotation entries. Check paths.")

    # 3. Shuffle and split
    print(f"\n[2/4] Splitting {len(matched)} images (train/val/test = "
          f"{TRAIN_RATIO:.0%}/{VAL_RATIO:.0%}/{1-TRAIN_RATIO-VAL_RATIO:.0%}) ...")
    random.seed(SEED)
    random.shuffle(matched)

    n_train = max(1, int(len(matched) * TRAIN_RATIO))
    n_val   = max(1, int(len(matched) * VAL_RATIO))
    splits = {
        "train": matched[:n_train],
        "val":   matched[n_train : n_train + n_val],
        "test":  matched[n_train + n_val :],
    }
    for split, items in splits.items():
        print(f"      {split:5s}: {len(items)} images")

    # 4. Write processed dataset
    print(f"\n[3/4] Writing processed dataset to {PROCESSED_DIR} ...")
    if PROCESSED_DIR.exists():
        shutil.rmtree(PROCESSED_DIR)

    counts = {}
    for split, items in splits.items():
        img_dir = PROCESSED_DIR / split / "images"
        lbl_dir = PROCESSED_DIR / split / "labels"
        img_dir.mkdir(parents=True)
        lbl_dir.mkdir(parents=True)

        box_count = 0
        for img_path, meta in items:
            # Copy image
            dst_img = img_dir / img_path.name
            shutil.copy2(img_path, dst_img)

            # Write label file
            lbl_path = lbl_dir / (img_path.stem + ".txt")
            lines = [
                xyxy_to_yolo(xtl, ytl, xbr, ybr, meta["width"], meta["height"])
                for xtl, ytl, xbr, ybr in meta["boxes"]
            ]
            lbl_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
            box_count += len(lines)

        counts[split] = {"images": len(items), "boxes": box_count}
        print(f"      {split:5s}: {len(items)} images, {box_count} boxes written")

    # 5. Write data.yaml
    print(f"\n[4/4] Writing data.yaml ...")
    write_yaml(PROCESSED_DIR)

    print("\n✅  Conversion complete!")
    print(f"    Dataset ready at: {PROCESSED_DIR}")
    print(f"    Total boxes: {sum(c['boxes'] for c in counts.values())}")
    return counts


if __name__ == "__main__":
    convert()
